### ISSUE TITLE
Undeclared Type

### ISSUE THREAD

**Issue by sujewan** [ZaidPathan/SpeechKitManager#1]
Getting this error, when I initialize speech kit variable
"Use of undeclared type 'SpeechKitManager"

Using - xCode 8.2 , Swift 3.0

**Comment by ZaidPathan** [comment]
Have you import SpeechKitManager?

Using,
```swift
import SpeechKitManager
```

**Comment by ZaidPathan** [comment]
@sujewan Please check my previous question.

**Comment by sujewan** [comment]
In my code, I am using 

import SpeechKitManager

**Comment by ZaidPathan** [comment]
@sujewan In your project can you check`SpeechKitManager.swift` file exists?
